### PR TITLE
change link to official aarch64 1.12 binary

### PR DESCRIPTION
**Pull request by yapishu**

### CODE REVIEW

**Comment by ar-jan** [comment]
Can now be updated to v1.13 already.

**Comment by hanryc-tirpur** [comment]
Any word on this? I am currently unable to update my proposal group to Groups 2.

**Comment by yapishu** [comment]
updated to use aarch64 latest link

**Comment by mopfel-winrux** [comment]
Closing this because I was able to get it to auto update

**Comment by mopfel-winrux** [comment]
Submitted a PR to for the latest update

https://github.com/getumbrel/umbrel-apps/pull/352

**Pull request closed without merging**
